version: '2'
services:
 web:
   image: tomcat:latest
   volumes:
    - ./OU_Spring.war:/usr/local/tomcat/webapps/OU_Spring.war
   ports:
    - "8080:8080"
   links:
    - db

 db:
  image: mysql:latest
  ports:
   - "3306:3306"
  volumes:
   - demo_volume:/var/lib/mysql
   - ./datadir:/docker-entrypoint-initdb.d
  environment:
   - "MYSQL_ROOT_PASSWORD=123456"
  command: mysqld --lower_case_table_names=1 --skip-ssl
   
volumes:
  demo_volume:
   driver: local